import * as esbuild from 'esbuild';

const config = {
  entryPoints: ['src/main.ts'], bundle: true, outfile: 'main.js',
  format: 'cjs', platform: 'browser', target: 'es2022',
  external: ['obsidian', 'electron', 'node:*', '@codemirror/*', '@lezer/*'],
  sourcemap: process.argv.includes('--watch') ? 'inline' : false,
  banner: { js: '/* Squid: independent Ink companion. Generated by esbuild. */' },
};
if (process.argv.includes('--watch')) {
  const context = await esbuild.context(config);
  await context.watch();
} else {
  await esbuild.build(config);
}
